namespace ArtistSearch.Tests;

// <auto-generated/>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Xunit;

// Validate that web scraping works.
public class ScrapeWebPage
{
    [InlineData("SomeLocalWebPage")]
    [Theory]
    public void Test1(string uri)
    {
        var _url = new Uri(uri);

    }
}
